/**
 * Business Category Enum
 * Categories for motorcycle-related businesses
 */
export enum BusinessCategory {
  REPAIR_MAINTENANCE = "REPAIR_MAINTENANCE",
  DEALERSHIPS_SALES = "DEALERSHIPS_SALES",
  PARTS_ACCESSORIES = "PARTS_ACCESSORIES",
  CUSTOMIZATION_TUNING = "CUSTOMIZATION_TUNING",
  MOTORCYCLE_RENTAL = "MOTORCYCLE_RENTAL",
  TIRES_WHEELS = "TIRES_WHEELS",
  DETAILING_WRAPPING = "DETAILING_WRAPPING",
  ROADSIDE_ASSISTANCE = "ROADSIDE_ASSISTANCE",
  GEAR_APPAREL = "GEAR_APPAREL",
  TRAINING_RIDING_SCHOOLS = "TRAINING_RIDING_SCHOOLS",
  MOTORCYCLE_CLUBS_COMMUNITIES = "MOTORCYCLE_CLUBS_COMMUNITIES",
  ELECTRIC_MOTORCYCLE_SERVICES = "ELECTRIC_MOTORCYCLE_SERVICES",
  PAINTING_BODYWORK = "PAINTING_BODYWORK",
  INSPECTION_LEGAL_SERVICES = "INSPECTION_LEGAL_SERVICES",
  TRANSPORTATION_STORAGE = "TRANSPORTATION_STORAGE",
}
