export enum ContentType {
  POST = "POST",
  POST_COMMENT = "POST_COMMENT",
  BUSINESS = "BUSINESS",
  BUSINESS_COMMENT = "BUSINESS_COMMENT",
  GROUP = "GROUP",
  EVENT = "EVENT",
  USER_PROFILE = "USER_PROFILE",
  WARNING = "WARNING",
  EMERGENCY = "EMERGENCY",
}
