export enum EmergencyType {
  ACCIDENT = "ACCIDENT",
  BREAKDOWN = "BREAKDOWN",
  MEDICAL = "MEDICAL",
  FUEL_SHORTAGE = "FUEL_SHORTAGE",
  TIRE_PROBLEM = "TIRE_PROBLEM",
  BATTERY_DEAD = "BATTERY_DEAD",
  LOST = "LOST",
  OTHER = "OTHER",
}
