/**
 * Equipment Type Enum
 */
export enum EquipmentType {
  FULL_FACE_HELMET = "FULL_FACE_HELMET",
  MODULAR_HELMET = "MODULAR_HELMET",
  OPEN_FACE_HELMET = "OPEN_FACE_HELMET",
  OFF_ROAD_HELMET = "OFF_ROAD_HELMET",
  HALF_HELMET = "HALF_HELMET",
  RIDING_JACKET = "RIDING_JACKET",
  ARMOR = "ARMOR",
  BACK_PROTECTOR = "BACK_PROTECTOR",
  AIRBAG_VEST = "AIRBAG_VEST",
  RIDING_PANTS = "RIDING_PANTS",
  KNEE_GUARDS = "KNEE_GUARDS",
  GLOVES = "GLOVES",
  BOOTS = "BOOTS",
  GOGGLES = "GOGGLES",
  RAIN_SUIT = "RAIN_SUIT",
  INTERCOM = "INTERCOM",
  CAMERA = "CAMERA",
  GPS_DEVICE = "GPS_DEVICE",
  FIRST_AID_KIT = "FIRST_AID_KIT",
}
