/**
 * Event Type Enum
 * Types of events
 */
export enum EventType {
  SOLO_RIDE = "SOLO_RIDE",
  GROUP_RIDE = "GROUP_RIDE",
  CAMPING_RIDE = "CAMPING_RIDE",
  MEET_UP = "MEET_UP",
  TRAINING = "TRAINING",
  MOTOFEST = "MOTOFEST",
  SOCIAL_RESPONSIBILITY = "SOCIAL_RESPONSIBILITY",
}
