/**
 * Interest Enum
 */
export enum Interest {
  BIKE_CUSTOMIZATION = "BIKE_CUSTOMIZATION",
  DIY_MAINTENANCE = "DIY_MAINTENANCE",
  VINTAGE_BIKES = "VINTAGE_BIKES",
  ELECTRIC_BIKES = "ELECTRIC_BIKES",
  RIDING_SKILLS = "RIDING_SKILLS",
  MOTO_PHOTOGRAPHY = "MOTO_PHOTOGRAPHY",
  CONTENT_CREATION = "CONTENT_CREATION",
  MEETING_RIDERS = "MEETING_RIDERS",
  COMMUNITY_EVENTS = "COMMUNITY_EVENTS",
  MOTO_FESTIVALS = "MOTO_FESTIVALS",
  EXPLORING_NATURE = "EXPLORING_NATURE",
  MOUNTAIN_ROADS = "MOUNTAIN_ROADS",
  COASTAL_RIDES = "COASTAL_RIDES",
  CROSS_BORDER_TRIPS = "CROSS_BORDER_TRIPS",
  RIDING_ABROAD = "RIDING_ABROAD",
}
