/**
 * Interest Enum
 */
export enum Interest {
  MOTORCYCLE_CUSTOMIZATION = "MOTORCYCLE_CUSTOMIZATION",
  DIY_MAINTENANCE = "DIY_MAINTENANCE",
  VINTAGE_MOTORCYCLES = "VINTAGE_MOTORCYCLES",
  ELECTRIC_MOTORCYCLES = "ELECTRIC_MOTORCYCLES",
  RIDING_SKILLS = "RIDING_SKILLS",
  MOTO_PHOTOGRAPHY = "MOTO_PHOTOGRAPHY",
  CONTENT_CREATION = "CONTENT_CREATION",
  MEETING_RIDERS = "MEETING_RIDERS",
  COMMUNITY_EVENTS = "COMMUNITY_EVENTS",
  MOTO_FESTIVALS = "MOTO_FESTIVALS",
  EXPLORING_NATURE = "EXPLORING_NATURE",
  MOUNTAIN_ROADS = "MOUNTAIN_ROADS",
  COASTAL_RIDES = "COASTAL_RIDES",
  CROSS_BORDER_TRIPS = "CROSS_BORDER_TRIPS",
}
