/**
 * Notification Type Enum
 * Types of notifications
 */
export enum NotificationType {
  SYSTEM = "SYSTEM",
  // Post notifications
  POST_LIKE = "POST_LIKE", // OK
  POST_COMMENT = "POST_COMMENT", // OK
  POST_SAVE = "POST_SAVE", // OK
  // User notifications
  USER_FOLLOW_REQUEST = "USER_FOLLOW_REQUEST", // OK
  USER_FOLLOW_REQUEST_ACCEPTED = "USER_FOLLOW_REQUEST_ACCEPTED", // OK
  NEW_FOLLOWER = "NEW_FOLLOWER", // OK
  // Group notifications
  SHARED_POST_IN_GROUP = "SHARED_POST_IN_GROUP", // OK
  GROUP_CHANGED_INFO = "GROUP_CHANGED_INFO", // OK
  GROUP_JOIN_REQUEST = "GROUP_JOIN_REQUEST", // OK
  GROUP_JOIN_REQUEST_ACCEPTED = "GROUP_JOIN_REQUEST_ACCEPTED", // OK
  USER_JOINED_GROUP = "USER_JOINED_GROUP", // OK
  USER_LEAVE_GROUP = "USER_LEAVE_GROUP", // OK
  ADMIN_REMOVED_GROUP_MEMBER = "ADMIN_REMOVED_GROUP_MEMBER", // OK
  ADMIN_CHANGED_GROUP_MEMBER_ROLE = "ADMIN_CHANGED_GROUP_MEMBER_ROLE", // OK
  // Event notifications
  EVENT_INVITATION = "EVENT_INVITATION", // OK
  EVENT_INVITATION_REMINDER = "EVENT_INVITATION_REMINDER",
  EVENT_REMINDER = "EVENT_REMINDER",
  EVENT_CANCELLED = "EVENT_CANCELLED", // OK
  EVENT_UPDATED = "EVENT_UPDATED", // OK
  // Emergency notifications
  EMERGENCY = "EMERGENCY",
  // Warning notifications
  WARNING = "WARNING",
}
