/**
 * Notification Type Enum
 * Types of notifications
 */
export enum NotificationType {
  SYSTEM = "SYSTEM",
  // Post notifications
  SHARED_POST_IN_GROUP = "SHARED_POST_IN_GROUP",
  POST_LIKE = "POST_LIKE",
  POST_COMMENT = "POST_COMMENT",
  POST_SAVE = "POST_SAVE",
  // User notifications
  USER_FOLLOW_REQUEST = "USER_FOLLOW_REQUEST",
  USER_FOLLOW_REQUEST_ACCEPTED = "USER_FOLLOW_REQUEST_ACCEPTED",
  NEW_FOLLOWER = "NEW_FOLLOWER",
  // Group notifications
  GROUP_CHANGED_INFO = "GROUP_CHANGED_INFO",
  GROUP_JOIN_REQUEST = "GROUP_JOIN_REQUEST",
  GROUP_JOIN_REQUEST_ACCEPTED = "GROUP_JOIN_REQUEST_ACCEPTED",
  USER_JOINED_GROUP = "USER_JOINED_GROUP",
  USER_LEAVE_GROUP = "USER_LEAVE_GROUP",
  ADMIN_REMOVED_GROUP_MEMBER = "ADMIN_REMOVED_GROUP_MEMBER",
  ADMIN_CHANGED_GROUP_MEMBER_ROLE = "ADMIN_CHANGED_GROUP_MEMBER_ROLE",
}
