export enum ReportReason {
  SPAM = "SPAM",
  HARASSMENT = "HARASSMENT",
  HATE_SPEECH = "HATE_SPEECH",
  INAPPROPRIATE_CONTENT = "INAPPROPRIATE_CONTENT",
  COPYRIGHT_VIOLATION = "COPYRIGHT_VIOLATION",
  FALSE_INFORMATION = "FALSE_INFORMATION",
  OTHER = "OTHER",
}
