/**
 * Riding Style Enum
 */
export enum RidingStyle {
  TOURING = "TOURING",
  COMMUTING = "COMMUTING",
  OFF_ROAD = "OFF_ROAD",
  ADVENTURE = "ADVENTURE",
  TRACK = "TRACK",
  CAFE_RACER = "CAFE_RACER",
  CRUISER = "CRUISER",
  SPORT = "SPORT",
  STUNT = "STUNT",
  GROUP_RIDE = "GROUP_RIDE",
  SOLO_RIDE = "SOLO_RIDE",
  TOURING_WITH_CAMPING = "TOURING_WITH_CAMPING",
  SCOOTER = "SCOOTER",
  CUSTOM = "CUSTOM",
}
