export enum WarningType {
  RADAR = "RADAR",
  POLICE_CHECKPOINT = "POLICE_CHECKPOINT",
  ACCIDENT = "ACCIDENT",
  ROAD_CONSTRUCTION = "ROAD_CONSTRUCTION",
  ROAD_CLOSURE = "ROAD_CLOSURE",
  DANGEROUS_CURVE = "DANGEROUS_CURVE",
  SLIPPERY_ROAD = "SLIPPERY_ROAD",
  PARKING_PROHIBITED = "PARKING_PROHIBITED",
  OTHER = "OTHER",
}
