/*
  Warnings:

  - The values [BEGINNER,ADVANCED,CITY_RIDES,TRACK_DAY,SCOOTER_GROUP,WOMEN_ONLY,WEEKEND_RIDERS,CROSS_COUNTRY,BORDER_RIDES,DIY_AND_CUSTOM,MECHANIC_DISCUSSION] on the enum `GroupTag` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "GroupTag_new" AS ENUM ('ADVENTURE', 'BEGINNERS_WELCOME', 'CAMPING', 'CHOPPER', 'CLASSIC_MOTORCYCLE', 'CULTURAL_TOURS', 'CUSTOM_MOTORCYCLE', 'DAILY_RIDE', 'ELECTRIC_MOTORCYCLE', 'ENDURO', 'EVENT_ORGANIZERS', 'EXPERIENCED_RIDERS', 'EXPLORATION', 'FAMILY_FRIENDLY', 'FUN_RIDES', 'INTERNATIONAL_RIDERS', 'MUSIC_CULTURE', 'OFF_ROAD', 'PHOTOGRAPHY', 'RIDER_EDUCATION', 'SCOOTER', 'SOCIAL_RESPONSIBILITY', 'TOURING', 'TRACK', 'VINTAGE_LOVERS', 'WOMEN_RIDERS', 'YOUNG_RIDERS');
ALTER TABLE "Group" ALTER COLUMN "tags" TYPE "GroupTag_new"[] USING ("tags"::text::"GroupTag_new"[]);
ALTER TYPE "GroupTag" RENAME TO "GroupTag_old";
ALTER TYPE "GroupTag_new" RENAME TO "GroupTag";
DROP TYPE "GroupTag_old";
COMMIT;
