/*
  Warnings:

  - The values [SALES,DEALERSHIP,USED_DEALER,REPAIR,MAINTENANCE,ENGINE_REPAIR,ENGINE_REBUILDING,ELECTRICAL_REPAIR,TIRE_SERVICE,OIL_CHANGE,BATTERY_SERVICE,BRAKE_SERVICE,SUSPENSION_REPAIR,TRANSMISSION_REPAIR,PARTS_STORE,ACCESSORIES,PROTECTIVE_GEAR,EXHAUST_SYSTEMS,ELECTRONICS,LIGHTING,INTERCOMS,RENTAL,TOWING,PARKING,STORAGE,CUSTOMIZATION,RESTORATION,INSPECTION,FINANCING,INSURANCE,TRADE_IN,ELECTRIC_MOTORCYCLES,SCOOTERS,ATV,DETAILED_CLEANING,TRAINING,TRANSPORT_SHIPPING,TOURS,OTHER] on the enum `BusinessCategory` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "BusinessCategory_new" AS ENUM ('REPAIR_MAINTENANCE', 'DEALERSHIPS_SALES', 'PARTS_ACCESSORIES', 'CUSTOMIZATION_TUNING', 'MOTORCYCLE_RENTAL', 'TIRES_WHEELS', 'DETAILING_WRAPPING', 'ROADSIDE_ASSISTANCE', 'GEAR_APPAREL', 'TRAINING_RIDING_SCHOOLS', 'MOTORCYCLE_CLUBS_COMMUNITIES', 'ELECTRIC_MOTORCYCLE_SERVICES', 'PAINTING_BODYWORK', 'INSPECTION_LEGAL_SERVICES', 'TRANSPORTATION_STORAGE');
ALTER TABLE "Business" ALTER COLUMN "category" TYPE "BusinessCategory_new" USING ("category"::text::"BusinessCategory_new");
ALTER TYPE "BusinessCategory" RENAME TO "BusinessCategory_old";
ALTER TYPE "BusinessCategory_new" RENAME TO "BusinessCategory";
DROP TYPE "BusinessCategory_old";
COMMIT;
