/**
 * Address Type Enum
 * Matches backend AddressType enum
 */
export enum AddressType {
  POST_LOCATION = 'POST_LOCATION',
  EVENT_MEETING_POINT = 'EVENT_MEETING_POINT',
  EVENT_START_LOCATION = 'EVENT_START_LOCATION',
  EVENT_FINISH_LOCATION = 'EVENT_FINISH_LOCATION',
}
